FROM ubuntu:18.04

ARG MPICH_VERSION="3.2"
ARG MPICH_MAKE_OPTIONS

RUN apt-get --yes -qq update \
 && apt-get --yes -qq upgrade \
 && apt-get --yes -qq install \
                      cmake \
                      cpio \
                      curl \
                      g++ \
                      gcc \
                      gfortran \
                      git \
                      wget \
                      python3-dev \
                      python3-pip \
                      virtualenv \
                      vim       \
 && apt-get --yes -qq clean \
 && rm -rf /var/lib/apt/lists/*


# Download, build, and install MPICH

RUN mkdir /tmp/mpich-src
WORKDIR /tmp/mpich-src
RUN wget http://www.mpich.org/static/downloads/${MPICH_VERSION}/mpich-${MPICH_VERSION}.tar.gz \
      && tar xfz mpich-${MPICH_VERSION}.tar.gz  \
      && cd mpich-${MPICH_VERSION}  \
      && ./configure ${MPICH_CONFIGURE_OPTIONS}  \
      && make ${MPICH_MAKE_OPTIONS} && make install \ 
      && rm -rf /tmp/mpich-src

#### ADD DEFAULT USER ####
ARG USER=mfix
ENV USER ${USER}
RUN useradd --user-group --create-home --shell /bin/bash mfix ;\
        echo "mfix ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

ENV USER_HOME /home/${USER}
RUN chown -R ${USER}:${USER} ${USER_HOME}

#### CREATE WORKING DIRECTORY FOR USER ####
ARG WORKDIR=/home/${USER}/mfix
ENV WORKDIR ${WORKDIR}
RUN mkdir ${WORKDIR}
RUN chown -R ${USER}:${USER} ${WORKDIR}

WORKDIR ${WORKDIR}

RUN mkdir -p mfix && \
    wget https:ef9c88b3/3d6affc7bf2813475bf1d847f8cb8d02//source/mfix/mfix-21.4.tar.gz && \
    tar -xzvf mfix-21.4.tar.gz &&  \
    cd mfix-21.4/tutorials/tfm/fluid_bed_2d/  && \
    cmake ../../.. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_MPI=1; make;

# Configure apache
RUN echo 'installed mfix' && \
    echo 'check mfix-21.4/tutorials/tfm/fluid_bed_2d/' ;

RUN echo 'Feel free to make changes to the code and build mfix'

USER ${USER}

RUN echo "export LB_BRARY_PATH='/usr/local/lib/:$LB_BRARY_PATH'" >> /home/mfix/.bashrc

RUN sed -i s/LB_BRARY_PATH/LD_LIBRARY_PATH/g /home/mfix/.bashrc
CMD ["/bin/bash"]
