#docker build -f Dockerfile_mpich  -t dockermpich .
FROM ubuntu:18.04

ARG MPICH_VERSION="3.2"
#ARG MPICH_CONFIGURE_OPTIONS="--disable-fortran"
ARG MPICH_MAKE_OPTIONS

RUN apt-get --yes -qq update \
 && apt-get --yes -qq upgrade \
 && apt-get --yes -qq install \
                      cmake \
                      cpio \
                      curl \
                      g++ \
                      gcc \
                      gfortran \
                      git \
                      wget \
                      python3-dev \
                      python3-pip \
                      virtualenv \
                      vim       \
 && apt-get --yes -qq clean \
 && rm -rf /var/lib/apt/lists/*


# Download, build, and install MPICH
RUN mkdir /tmp/mpich-src
WORKDIR /tmp/mpich-src
RUN wget http://www.mpich.org/static/downloads/${MPICH_VERSION}/mpich-${MPICH_VERSION}.tar.gz \
      && tar xfz mpich-${MPICH_VERSION}.tar.gz  \
      && cd mpich-${MPICH_VERSION}  \
      && ./configure ${MPICH_CONFIGURE_OPTIONS}  \
      && make ${MPICH_MAKE_OPTIONS} && make install \
      && rm -rf /tmp/mpich-src


#### ADD DEFAULT USER ####
ARG USER=mpi
ENV USER ${USER}
RUN useradd --user-group --create-home --shell /bin/bash mpi ;\
        echo "mpi ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

ENV USER_HOME /home/${USER}
RUN chown -R ${USER}:${USER} ${USER_HOME}

#### CREATE WORKING DIRECTORY FOR USER ####
ARG WORKDIR=/project
ENV WORKDIR ${WORKDIR}
RUN mkdir ${WORKDIR}
RUN chown -R ${USER}:${USER} ${WORKDIR}

WORKDIR ${WORKDIR}
USER ${USER}


CMD ["/bin/ash"]

#docker run -it dockermpich bash
#wget https://github.com/mpitutorial/mpitutorial.git 
#cd mpitutorial/tutorials/mpi-hello-world/code && make &&  
#mpirun -np 4 ./mpi_hello_world
#
#
#docker login --username kvmkrao
#docker tag dockermpich kvmkrao/mpich
#docker push kvmkrao/mpich
